spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fintech_rag}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/finassist}
  ai:
    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}

keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8180}
    realm: ${KEYCLOAK_REALM:finassist}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:finassist-admin}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
